[server]
host = "127.0.0.1"
port = "8080"

[database]
host = "127.0.0.1"
port = "5432"
user = "postgres"
max_connections = 30

[logging]
level = "info"
sink = { type = "file" , path = "./tests/app.log" }
format = "compact" # compact or json