[package]
name = "log-internal"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
config-internal = {workspace = true}
console-subscriber = {workspace = true}
tracing = {workspace = true}
tracing-reload = {workspace = true}
tracing-subscriber = {workspace = true}